version: '3.8'

services:
  app:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    ports:
      - "5432:5432"
