version: '3.8'

services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
